project:
  type: website
  output-dir: docs

website:
  title: "rachel-ramos-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: portfolio-project/Ramos-FinalProject.qmd
        text: "Ramos-FinalProject"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
